---
- name: Install dependencies
  ansible.builtin.import_tasks: dependencies.yml
  become: true
  tags:
    - install_dependencies 

- name: Build authentik
  ansible.builtin.import_tasks: build.yml
  become: true
  tags:
    - build
  become_user: authentik
