---
- name: Install dependencies
  ansible.builtin.import_tasks: dependencies.yml
  become: true
  tags:
    - install_dependencies

- name: Build authentik
  ansible.builtin.import_tasks: build.yml
  become: true
  tags:
    - build
  become_user: authentik

- name: Create useful directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: authentik
  with_items:
    - /opt/authentik/certs
    - /opt/authentik/media
    - /etc/authentik

- name: Test
  ansible.builtin.copy:
    remote_src: true
    src: /opt/authentik/src/blueprints
    dest: /opt/authentik/blueprints
    owner: authentik
  become: true
