---
- name: Install fail2ban
  ansible.builtin.apt:
    name: "fail2ban"
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Install fail2ban
  ansible.builtin.dnf:
    name: "fail2ban"
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Copy sshd.conf
  ansible.builtin.template:
    src: 'sshd.conf.j2'
    dest: '/etc/fail2ban/jail.d/sshd.conf'
    mode: "0640"
  notify:
    - Restart fail2ban

- name: Start fail2ban.service
  ansible.builtin.systemd:
    state: started
    name: fail2ban.service
    enabled: true
