---
- name: Configure base
  hosts: all
  become: true
  roles:
    - role: dnf
      when: ansible_facts['os_family'] == "RedHat"
    - auditd
    - fail2ban
    - journald
    - sshd
    - role: timesyncd
      when: ansible_facts['os_family'] == "Debian"
    - role: ufw
      when: ansible_facts['os_family'] == "Debian"

- name: Resolver
  hosts: resolver
  become: true
  roles:
    - knot_resolver
