---
- name: Configure base
  hosts: all
  become: true
  roles:
    - role: dnf
      when: ansible_facts['os_family'] == "RedHat"
    - auditd
    - fail2ban
    - journald
    - sshd
    - role: timesyncd
      when: ansible_facts['os_family'] == "Debian"
    - role: ufw
      when: ansible_facts['os_family'] == "Ubuntu"

- name: Resolver
  hosts: resolver
  become: true
  roles:
    - knot_resolver

- name: DHCP
  hosts: kea-dhcp
  become: true
  roles:
    - kea_dhcp

- name: Knot
  hosts: dns-authoritative
  become: true
  roles:
    - knot
