<<<<<<< HEAD
---
=======
>>>>>>> 2410885 (Add knot roles)
all:
  hosts:
    resolver-1:
      ansible_host: 10.20.0.42
<<<<<<< HEAD
    dhcp-1:
      ansible_host: 10.20.0.43
    authoritative-1:
      ansible_host: 10.20.0.44
=======
>>>>>>> 2410885 (Add knot roles)
  children:
    resolver:
      hosts:
        resolver-1:
<<<<<<< HEAD
    kea-dhcp:
      hosts:
        dhcp-1:
    dns-authoritative:
      hosts:
        authoritative-1:
=======
>>>>>>> 2410885 (Add knot roles)
