---
all:
  hosts:
    resolver-1:
      ansible_host: 10.20.0.42
    dhcp-1:
      ansible_host: 10.20.0.43
    authoritative-1:
      ansible_host: 10.20.0.44
  children:
    resolver:
      hosts:
        resolver-1:
    kea-dhcp:
      hosts:
        dhcp-1:
    dns-authoritative:
      hosts:
        authoritative-1:
