---
- name: Upgreade
  hosts: all
  become: true
  tasks:
    - name: Ugrade debian based
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      when: ansible_facts['os_family'] == "Debian"
   
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
