---
- name: Restart isc-kea-dhcp4-server
  become: true
  ansible.builtin.service:
    state: restarted
    name: isc-kea-dhcp4-server

- name: Enable isc-kea-dhcp4-server
  ansible.builtin.service:
    enabled: true
    name: isc-kea-dhcp4-server
